package com.example.pharmaaggregatorserver.repository.product;

import com.example.pharmaaggregatorserver.entity.product.ProductAttributeSupplementsOrNutraceuticals;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ProductAttributeSupplementsOrNutraceuticalsRepository extends JpaRepository<ProductAttributeSupplementsOrNutraceuticals, String> {
}
