server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

app:
  login-url: http://localhost:3000/reset-password
  frontend-url: http://localhost:3000
  admin-frontend-url: http://localhost:3000
  reset-token-expiration-hours: 1
  jwt:
    secret: mySecretKeyForJWTTokenGenerationAndValidation2024!@#$%^&*
    expiration: 86400000


spring:

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${POSTGRES_URL}
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:   # Email configuration
    host: smtp.gmail.com
    port: 587
    username: basavarajunn@tiameds.ai
    password: ovfx kzmu ikhg rily
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


#  # Twilio sms
#twilio:
#  account-sid: ${ACCOUNT_SID}
#  auth-token: ${AUTH_TOKEN}
#  verify:
#    service-sid: ${SERVICE_SID}

twilio:
  account-sid: ${ACCOUNT_SID}
  auth-token: ${AUTH_TOKEN}
  verify:
    service-sid: ${SERVICE_SID}

#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#    include-exception: true
#    include-stacktrace: always


springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true


logging:
  level:
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG

    org.springframework.web: DEBUG

    org.springframework.security: DEBUG

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG

    com.fasterxml.jackson.databind: DEBUG

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}