server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

app:
  frontend-url: http://localhost:3000
  reset-token-expiration-hours: 1
  jwt:
    secret: mySecretKeyForJWTTokenGenerationAndValidation2024!@#$%^&*
    expiration: 86400000


spring:

  main:
    allow-bean-definition-overriding: true

  datasource:

    # DB_HOST=localhost when running locally; set DB_HOST=postgres-dev when using docker-compose
    url: jdbc:postgresql://host.docker.internal:5432/pharma-aggregator?charSet=UTF8
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:   # Email configuration
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



#  # Twilio sms
#twilio:
#  account-sid: ${ACCOUNT_SID}
#  auth-token: ${AUTH_TOKEN}
#  verify:
#    service-sid: ${SERVICE_SID}

twilio:
  account-sid: ${ACCOUNT_SID:dummy_sid}
  auth-token: ${AUTH_TOKEN:dummy_token}
  verify:
    service-sid: ${SERVICE_SID:dummy_service}

#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#    include-exception: true
#    include-stacktrace: always


springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true


logging:
  level:
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG

    org.springframework.web: DEBUG

    org.springframework.security: DEBUG

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG

    com.fasterxml.jackson.databind: DEBUG
